### ISSUE TITLE
Дописать в readme, что page.html нужно самостоятельно в книге разместить

### ISSUE THREAD

**Issue by pongo** [mikaspell/gitbook-plugin-yametrika#3]
Здравствуйте!

Спасибо за плагин, все работает. Но есть одно пожелание:

Укажите в readme что `_layouts/website/page.html` нужно самостоятельно размещать на гитбуке.

**Comment by mathbunnyru** [comment]
@pongo я правильно понимаю, что для этого нужно просто добавить этот файл по указанному путю в репозиторий с книгой?

**Comment by mathbunnyru** [comment]
А если книга мультиязычная, то для каждого языка?

**Comment by pongo** [comment]
@mathbunnyru да, просто добавить. С мультиязычными книгами не сталкивался - попробуйте разные варианты.

**Comment by mathbunnyru** [comment]
@pongo спасибо. К сожалению, с мультиязычной книгой возникают проблемы - я положил этот файлик и в ru, и в en и внутри этих папок скрипт успешно добавился к концу сгенеренного файла, а вот корневой index.html, к сожалению, никак не изменился, и поэтому ничего не работает (метрика настроена конечно на оcновной сайт). Если вы знаете, как это вылечить, было бы очень круто.

@mikaspell здравствуйте, не могли бы вы пожалуйста помочь с решением проблемы?

**Comment by mikaspell** [comment]
@mathbunnyru Приветствую. а можете скинуть репозиторий мультиязычной книги?

**Comment by mathbunnyru** [comment]
https://github.com/hftbattle/documentation - это репоз, а сайт вот здесь - https://docs.hftbattle.com

**Comment by mikaspell** [comment]
@mathbunnyru на выходных посмотрю и сделаю

**Comment by mathbunnyru** [comment]
Спасибо!

**Comment by mathbunnyru** [comment]
@mikaspell добрый день! есть успехи?

**Comment by mikaspell** [comment]
@mathbunnyru в процессе, пару дней еще потерпите)

**Comment by mathbunnyru** [comment]
@mikaspell окей, спасибо))

**Comment by mathbunnyru** [comment]
@mikaspell пока не получается?

**Comment by ezakhar** [comment]
@mathbunnyru, аналогичная проблема.
Решил пока следующим образом. Создал два счетчика в метрике, один на русскую, второй на английскую версию мультиязычной книги. 
В page.html для каждой книги добавил код счетчика, сгенерированный Яндексом.
Плагин отключил.

**Comment by mathbunnyru** [comment]
@ezakhar спасибо, я как раз тогда думал, что так наверно можно сделать:) Просто ждал, что плагин починят.

**Comment by mikaspell** [comment]
@pongo @mathbunnyru @ezakhar Обновите плагин, исправлено. Оказывается забыл опубликовать плагин в npm.
